version: '3.8'
services:
  discord-bot:
    build: .
    container_name: pxk-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./data:/app/data
